### ISSUE TITLE
Capitalized filename extensions e.g. 'JPG' vs 'jpg' 

### ISSUE THREAD

**Issue by trevorbroaddus** [marc1706/fast-image-size#14]
I ran into a circumstance where a file URL had an all caps file extension i.e. '.JPG' instead of expected '.jpg', but the regex in FastImageSize::getImageSize() only matches lower-case. I propose matching upper-case letters as well, then passing the resulting matched extension through 'strtolower()' before sending to FastImageSize::getImageSizeByExtension().

**Comment by marc1706** [comment]
Thanks for the report. Can you confirm the linked pull request fixes the issue?
