### ISSUE TITLE
Error to get image size

### ISSUE THREAD

**Issue by adonisfigueroa** [marc1706/fast-image-size#22]
I get this error:
PHP Notice:  Uninitialized string offset: 25214 in ....lib/Type/TypeJpeg.php on line 128

I use this code:
$FastImageSize = new \FastImageSize\FastImageSize();
$imageSize = $FastImageSize->getImageSize('http://www.techspot.com/articles-info/1121/images/P34WS-12.jpg');
print_r($imageSize);

The same error you can get with these images:
http://www.techspot.com/articles-info/1121/images/P34WS-4.jpg
http://www.techspot.com/articles-info/1121/images/P34WS-17.jpg

**Comment by 3zzy** [comment]
I came here to report the exact same issue and found this. Is it resolved?

```
PHP Notice:  Uninitialized string offset: 73122 in /vendor/marc1706/fast-image-size/lib/Type/TypeJpeg.php on line 128
Notice: Uninitialized string offset: 73122 in /vendor/marc1706/fast-image-size/lib/Type/TypeJpeg.php on line 128

PHP Notice:  Uninitialized string offset: 73123 in /vendor/marc1706/fast-image-size/lib/Type/TypeJpeg.php on line 128
Notice: Uninitialized string offset: 73123 in /vendor/marc1706/fast-image-size/lib/Type/TypeJpeg.php on line 128
```

**Comment by adonisfigueroa** [comment]
No solution yet.

**Comment by marc1706** [comment]
Can you please check if the proposed pull request fixes the aforementioned issues?

**Comment by adonisfigueroa** [comment]
No errors, but I can't get the size yet, so the real problem persists

**Comment by marc1706** [comment]
I've updated the pull request to take care of further issues that popped up during debugging with the mentioned images.
