### ISSUE TITLE
Filename casing issues

### ISSUE THREAD

**Issue by echosa** [marc1706/fast-image-size#30]
In this directory: https://github.com/marc1706/fast-image-size/tree/bafc33cc5315e5636674d3639bda98a07d33e7b9/tests/fixture

There are files `JPG` and `PNG` as well as `jpg` and `png`.  This is an issue for case-insensitive systems like Windows and OS X/macOS (by default). I noticed when when using `unison` to sync files between a VM and a host machine. Unison kept reporting skipped files:

```
  skipped: vendor/marc1706/fast-image-size/tests/fixture/jpg (Two or more files on a case-sensitive system have names identical except for case.  They cannot be synchronized to a case-insensitive file system.  (File 'vendor/marc1706/fast-image-size/tests/fixture/jpg'))
  skipped: vendor/marc1706/fast-image-size/tests/fixture/png (Two or more files on a case-sensitive system have names identical except for case.  They cannot be synchronized to a case-insensitive file system.  (File 'vendor/marc1706/fast-image-size/tests/fixture/png'))
```

In checking my host machine files, I noticed that I didn't have any files `jpg` or `png` at all. On the VM, where the repo was initially checked out/installed by composer, I see `jpg` and `JPG`. The VM is case-sensitive, so it works fine. The host machine is not.

Is there a way you can change this so that you don't have file name conflicts on case-insensitive file systems?

**Comment by marc1706** [comment]
Sure, shouldn't be an issue to rename them to not conflict on those. FWIW, if you install this package with composer you shouldn't be getting the tests directory and therefore also won't end up with this issue: ;)

**Comment by echosa** [comment]
@marc1706 I didn't install this directly. It is a dependency of a dependency of a package I installed. Not sure I can control the installation of tests in that case, but it'd still be good to fix this, in case someone did want the tests on a case-insensitive file system so that they could run them/fix a bug. :-)

**Comment by echosa** [comment]
@marc1706 So, before I go through the trouble of forking this repo, removing the tests, then forking another library, and modifying it to use my forked version of this repo, I'd like to see if this can get fixed here in the main repo first. You said "shouldn't be an issue to rename them to not conflict on those", but looking at the test, the casing is important, so I'm guessing the files would need to be renamed to something else that's still all caps, but doesn't conflict with a lower case version of the same name. I'm not sure the best way to handle it, so I'm not comfortable sending in a PR. Is that something you could take care? If you can't get to it very soon, that's fine. Just let me know, and I'll fork. Just figured I'd try to save myself some trouble. Programmers are supposed to be lazy, right? ;-)

**Comment by marc1706** [comment]
Closing as PR for this was merged.
