### ISSUE TITLE
Jpeg format not working

### ISSUE THREAD

**Issue by zeppaman** [marc1706/fast-image-size#31]
I have some jpeg images not working with library.One of the images I'm using is attached to the issue. 

The issue seems to be :
`$this->data = $this->fastImageSize->getImage($filename, 0, self::JPEG_MAX_HEADER_SIZE, false); `

on file
[https://github.com/marc1706/fast-image-size/blame/master/lib/Type/TypeJpeg.php](url)

it returns an empty object even if the image is a jpeg.

I already tried to change extension of file from "jpg" to "jpeg". I tried aslo to expand max header size, but with no results.

![xlarge_img_20150602_134657](https://cloud.githubusercontent.com/assets/5618315/22625540/1a00d970-eb9a-11e6-95ec-a6991c28c4f9.jpg)

**Comment by marc1706** [comment]
That image works fine for me on the latest release. What version are you using and how exactly are you calling the library?

**Comment by zeppaman** [comment]
Thanks for the reply.
I'm sure it is the last version. I used composer to download it, moreover I also tested file with win merge and my are the same of /lib/ folder in repo.

Maybe this error could be due to the file name? It is: xlarge_IMG_20150602_134657.jpg, and no triki charachters on path, also no whitespaces.

By the way, I solved my issues by changing application and it is working well (I use max size when library is not able to provide real size), so if you are not interested on further test to find possible bugs on library we can close the issue.

Thanks for your time and for providing this useful library. It's a great job.

**Comment by marc1706** [comment]
Please also take a look at #34 and its pull request. I've also added the above image to my test fixtures as it's good mix of both EXIF and JFIF data. If you're not ok with this, please give me a heads up and I'll remove it again. I'll close this issue after releasing 1.1.3 as I take it that the issue has already been resolved in the mean time.

**Comment by marc1706** [comment]
Closing now that 1.1.3 has been released:
https://github.com/marc1706/fast-image-size/releases/tag/v1.1.3
