### ISSUE TITLE
Please tag a new release

### ISSUE THREAD

**Issue by echosa** [marc1706/fast-image-size#33]
The latest fixes, including the casing issue I previously reported (thank you for fixing that!), are not in a tagged release. The AMP library, which depends on yours, pulls `1.*`: https://github.com/Lullabot/amp-library/blob/bdf10c4470e7503d3bd187ba3afee7ecea008a7f/composer.json#L17

Please tag a newer `1.*` release so that composer will pull in the latest fixes. Thanks again!

**Comment by marc1706** [comment]
Already on it. Was still looking into an issue with JPEG files only using EXIF (see #34).

**Comment by marc1706** [comment]
Done: https://github.com/marc1706/fast-image-size/releases/tag/v1.1.3

**Comment by echosa** [comment]
Thanks!
