### ISSUE TITLE
Retrieve image size info from EXIF IFD if possible

### ISSUE THREAD

**Issue by marc1706** [marc1706/fast-image-size#34]
Some images saved with newer versions of Photoshop no longer carry the JFIF data but only the EXIF data including EXIF IFD. As a result of that, image size info needs to be extracted from EXIF instead of the JFIF header.

**Comment by 3D-I** [comment]
https://www.phpbb.com/community/viewtopic.php?p=14796976#p14796976

**Comment by Galixte** [comment]
Hi @3D-I is there any ticket opened on tracker for that?

**Comment by Galixte** [comment]
https://tracker.phpbb.com/browse/PHPBB3-15359

**Comment by marc1706** [comment]
Thanks, already looking into that and created an issue for it: https://github.com/marc1706/fast-image-size/issues/40
