### ISSUE TITLE
Can't find dimensions for TIFF files

### ISSUE THREAD

**Issue by Getekid** [marc1706/fast-image-size#36]
I'm using FastImageSize in phpBB 3.2.0 !

When uploading TIFF images in a post I get an error for failing to get the dimensions of the file. However when I change the `TIF_HEADER_SIZE` number e.g. to 512000 (in `lib\Type\TypeTif.php`) then it works.

**Comment by marc1706** [comment]
Could you upload the TIFF on here, preferably in a zipped form to prevent github possibly modifying it during upload? That would help with tracking this down.
I think it might make sense to take care of this with https://github.com/marc1706/fast-image-size/pull/26 as well

**Comment by Getekid** [comment]
Hello,

You can try with a [Sample file](http://www.fileformat.info/format//tiff/sample/index.htm), it has the same behavior.

Hope it helps, let me know in case you need more info for the problem. Thanks
