### ISSUE TITLE
Hidden dependency of mbstring not needed

### ISSUE THREAD

**Issue by loumray** [marc1706/fast-image-size#39]
This package has a hidden dependency that is actually not needed.

mbstring functions are used but seems to be not needed at all.

They occured only at this line.
https://github.com/marc1706/fast-image-size/blob/5f7e8377746524e2b8a49a631c1fc9afeb9d8bee/lib/FastImageSize.php#L81

Replacing this line by something like this would remove dependency to mbstring
`$className = '\FastImageSize\Type\Type' . ucfirst($imageType);`

Since the content of $imageType is defined from class parameter, there should be no need to rely on mbstring functions.

Either that or update composer.json to require ext-mbstring module, so that at least mbstring dependency is not hidden.

**Comment by marc1706** [comment]
Unfortunately this seems to be needed (see https://github.com/marc1706/fast-image-size/issues/18). Will add it as a requirement in composer.json.
